services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipb-reserve-backend:latest
    container_name: ipb-reserve-backend
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      # Automatically configure these variables from host environment
      - DATABASE_URL
      - FIREBASE_CREDENTIALS
      - INITIAL_ADMIN_EMAILS
      - PORT
    restart: unless-stopped
